### PR TITLE
Assignment 1 Submission

### PR DESCRIPTION
**Pull request by tlallas**
tlallas

### CODE REVIEW

**Comment by vishnuravi** [comment]
Hey @tlallas I see that you have committed all your image assets and swift files, but it seems like your xcode project file hasn't been committed? I'm still seeing the original file here: https://github.com/tlallas/AssignmentOne/blob/main/Assignment%20One.xcodeproj/project.pbxproj

**Comment by tlallas** [comment]
> Hey @tlallas I see that you have committed all your image assets and swift files, but it seems like your xcode project file hasn't been committed? I'm still seeing the original file here: https://github.com/tlallas/AssignmentOne/blob/main/Assignment%20One.xcodeproj/project.pbxproj

I only edited files in the Assignment One sub-directory of the assignment one project file. Is there any action I am supposed to have taken / what should the xcode project file look like?

**Comment by vishnuravi** [comment]
The xcode project file should have automatically updated as you added new files to the project. It should list all the new files you created/added (see https://github.com/cs342/AssignmentOne/blob/main/Assignment%20One.xcodeproj/project.pbxproj for an example). If your project is building properly, what may have happened is the changes in the project file weren't captured when committing to github. If you do a **git status**, does it show any changes in the .pbxproj file that aren't committed?

**Comment by tlallas** [comment]
Okay, I just committed the updated project file. Let me know if you are able to see this as expected:

Simulator Screen Shot - iPhone 12 - 2022-01-17 at 18 09 41

**Comment by vishnuravi** [comment]
It looks like your Xcode project file is updated now, I can see all your swift files in the navigator! The compiler is still complaining that "highlights.json" is missing, though. I don't see it referenced in your code anywhere - is it necessary for anything? If not, I'll just delete the reference to it in the project file and it should compile.

**Comment by tlallas** [comment]
highlights.json is not necessary! Feel free to delete. Sorry about all this!

**Comment by vishnuravi** [comment]
No worries, it compiles now! This is amazing!! I absolutely love the layout, especially the highlight reel! You are a SwiftUI Pro! 🥇

**Pull request merged**
